Add file to Playbook/ Business
dwarvesf/playbook pull request #41
Opened 2021-02-08 09:57 UTC by Lizzie14

Add 5 files:
1. Business playbook outline
2. Collaboration guideline
3. DF Workflow
4. General questions for service feedback
5. How to work with Clients - Account View

#### What's this PR do?

- [x] Add new routes for user
- [x] Add instruction for using docker-compose

#### What are the relevant Git tickets?

// Put in link to Git Issue

#### Screenshots (if appropriate)

// Use [Licecap](http://www.cockos.com/licecap/) to share a screencast gif.

#### Any background context you want to provide? (if appropriate)

- Is there a blog post?
- Does the knowledge base need an update?
- Does this add new dependencies which need to be added to?

2021-02-08 11:04 UTC, huynguyenh requested changes

2021-02-08 11:04 UTC, huynguyenh commented on business/Collaboration Guideline.md
> +# Collaboration Guideline
rename the file name to collaboration-guideline.md

2021-02-08 11:04 UTC, huynguyenh commented on business/DF workflow.md
> +* Monday:
rename the file name to df-workflow

2021-02-08 11:04 UTC, huynguyenh commented on business/General question for service feedbacks.md
> +# GENERAL QUESTIONS FOR SERVICE FEEDBACKS
rename the filename

2021-02-08 11:04 UTC, huynguyenh commented on business/How To Work With Clients - Account view.md
> +# TRAINING COURSE: HOW TO WORK WITH CLIENT
rename the filename

2021-02-09 11:44 UTC, huynguyenh approved these changes

2021-02-11 11:45 UTC, tieubao commented
@huynguyenh please double check if it still has any misleading information

2021-02-12 08:30 UTC, merged