docs: update db migration, environment and restful api practicesC
dwarvesf/playbook pull request #56
Opened 2022-09-14 17:03 UTC by vdhieu

#### What's this PR do?
Add best practices for
- [x] RestFul API
- [x] Database migration
- [x] Environment

2022-09-15 02:45 UTC, zlatanpham approved these changes
LGTM. Let @hieuphq take a quick look

2022-09-15 03:03 UTC, hieuphq requested changes

2022-09-15 03:03 UTC, hieuphq commented on engineering/backend/restful.md
> +- We prefer Swagger for REST API documentation. Alternative can be postman
```suggestion
- We prefer Swagger for REST API documentation.
```
we can use a tool to generate postman file from swagger

2022-09-15 03:03 UTC, hieuphq commented on engineering/backend/restful.md
> +- The API should return `previousCursor` and `nextCursor`
should describe how we structure the cursor from the backend and use from client

2022-09-15 03:03 UTC, hieuphq commented on engineering/backend/db-migration.md
> +
remove the empty line

2022-09-15 03:03 UTC, hieuphq commented on engineering/backend/db-migration.md
> +
remove the empty line

2022-09-15 03:03 UTC, hieuphq commented on engineering/backend/db-migration.md
> +
remove the empty line

2022-09-19 05:33 UTC, hieuphq requested changes

2022-09-19 05:33 UTC, hieuphq commented on engineering/backend/restful.md
> +- `cursor` - is the reference element in the list. Best brattice for choosing the cursor is only sort by unique sequential column, create new column which is concatenate columns if you have to order
```suggestion
- `cursor` - is the reference element in the list. The best practice for choosing the cursor is only sorting by a unique sequential column, and creating a new concatenate column if you have to order by multiple none unique columns.
```

2022-09-19 05:33 UTC, hieuphq commented on engineering/backend/restful.md
> +GET /companies?start=2022-09-10T05:10:55.308Z&end=2022-09-11T05:10:55.308Z
how can we filter 2+ DateTime fields with this convention?

2022-09-19 05:33 UTC, hieuphq commented on engineering/environment.md
> +- `Do not` commit your `.env` file or hard coded secret variables
```suggestion
- **Do not** commit your `.env` file or hard-coded secret variables. We must set up our project in the `.gitignore` file.
```

2022-09-19 05:33 UTC, hieuphq commented on engineering/environment.md
> +  - `.env.example` can commit t source code store default public variables, all private or secret values must not included in this file
```suggestion
  - `.env.example` can commit source code store default public variables, all private or secret values must not include in this file
```

2022-09-19 05:33 UTC, hieuphq commented on engineering/backend/restful.md
> +# Filter by time range
It makes me confused about the markdown convention. As we knew, One # character for Heading 1. We should update the way we index the headings.
```suggestion
#### Filter by category
GET /companies?category=software

#### Filter by locations
GET /companies?location=saigon&location=hanoi

#### Filter by time range
```

2022-09-20 08:04 UTC, monotykamary requested changes
Just some nits; otherwise, LGTM 👍

For extras, specifically for environment, it might be worthwhile to mention local file ignoring with `$GIT_DIR/info/exclude` or `git update-index --skip-worktree <file-list>`.

2024-04-19 03:40 UTC, closed without merging